const columns = [
    {name: "ID", uid: "id", sortable: true},
    {name: "TITLE", uid: "TITLE", sortable: true},
    {name: "DESCRIPTION", uid: "DESCRIPTION", sortable: true},
    {name: "PRICE", uid: "PRICE", sortable: true},
    {name: "DATE", uid: "DATE"},
    {name: "STATUS", uid: "STATUS", sortable: true},
    {name: "ACTIONS", uid: "ACTIONS"},
  ];
  
  const statusOptions = [
    {name: "Active", uid: "active"},
    {name: "Paused", uid: "paused"},
    
  ];
  
  const users = [
    {
      id: 1,
      title: "Tony Reichert",
      description: "CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    },
    {
      id: 2,
      title: "Zoey Lang",
      description: "CEO a CEO",
      price: '250',
      date: "29-07-2023",
      status: "paused",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    },
    {
      id: 3,
      title: "Jane Fisher",
      description: "CEO a CEO",
      price: '100',
      date: "29-07-2023",
      status: "paused",
      avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    },
    {
      id: 4,
      title: "William Howard",
      description: "CEO a CEO",
      price: '120',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    },
    {
      id: 5,
      title: "Kristen Copper",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    },
    {
      id: 6,
      title: "Brian Kim",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    },
    {
      id: 7,
      title: "Michael Hunt",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    },
    {
      id: 8,
      title: "Samantha Brooks",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    },
    {
      id: 9,
      title: "Frank Harrison",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    {
      id: 10,
      title: "Emma Adams",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    {
      id: 11,
      title: "Brandon Stevens",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
    {
      id: 12,
      title: "Megan Richards",
      description: "CEO a CEO",
      price: '200',
      date: "29-07-2023",
      status: "active",
      avatar: "https://i.pravatar.cc/150?img=10",
    },
    
  ];
  
  export {columns, users, statusOptions};